
spring:
h2:
console:
path: /h2-console
settings.trace: false
settings.web-allow-others: false
enabled: true
datasource:
driver-class-name: org.h2.Driver
url: jdbc:h2:mem:h2
username: sa
password:
jpa:
hibernate:
ddl-auto: create-drop
show-sql: false
database: postgresql
database-platform: org.hibernate.dialect.H2Dialect
generate-ddl: false
open-in-view: false